"""cascading update

Revision ID: 20e8589cda40
Revises: bcbdf2457f3a
Create Date: 2026-01-05 06:39:46.721849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e8589cda40'
down_revision: Union[str, None] = 'bcbdf2457f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coach_client_link_coach_id_fkey', 'coach_client_link', type_='foreignkey')
    op.drop_constraint('coach_client_link_client_id_fkey', 'coach_client_link', type_='foreignkey')
    op.create_foreign_key(
        'coach_client_link_client_id_fkey',  # New constraint name
        'coach_client_link',                 # Source table
        'users',                             # Referenced table
        ['client_id'],                       # Local columns (list)
        ['user_id'],                         # Remote columns (list)
        onupdate='CASCADE',
        ondelete='CASCADE'               
    )
    op.create_foreign_key(
        'coach_client_link_coach_id_fkey',  # New constraint name
        'coach_client_link',                # Source table
        'users',                            # Referenced table
        ['coach_id'],                       # Local columns (list)
        ['user_id'],                        # Remote columns (list)
        onupdate='CASCADE',
        ondelete='CASCADE'               
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('coach_client_link_coach_id_fkey', 'coach_client_link', type_='foreignkey')
    op.drop_constraint('coach_client_link_client_id_fkey', 'coach_client_link', type_='foreignkey')
    
    # Re-create original constraints (without CASCADE if that was the original state)
    op.create_foreign_key('coach_client_link_client_id_fkey', 'coach_client_link', 'users', ['client_id'], ['user_id'])
    op.create_foreign_key('coach_client_link_coach_id_fkey', 'coach_client_link', 'users', ['coach_id'], ['user_id'])
    # ### end Alembic commands ###
