"""set default user_id until users login with google

Revision ID: 54442024f29b
Revises: 5f28e060d7ec
Create Date: 2026-01-05 02:01:13.536751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = '54442024f29b'
down_revision: Union[str, None] = '5f28e060d7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.String(),
               nullable=False,
               existing_server_default=str(uuid.uuid4()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
