"""add coach client link

Revision ID: b84177e3c1b3
Revises: cd0e36605f38
Create Date: 2026-01-05 00:09:04.672786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b84177e3c1b3'
down_revision: Union[str, None] = 'cd0e36605f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_client_link',
    sa.Column('coach_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.Column('updated', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('coach_id', 'client_id')
    )
    op.add_column('users', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="jobseeker"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('coach_client_link')
    # ### end Alembic commands ###
