name: Deploy Frontend to AWS Lightsail
description: Deploy frontend application to AWS Lightsail

inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-region:
    description: AWS Region
    required: true
  aws-secret-access-key:
    description: AWS Access Key Secret
    required: true
  app-url:
    description: Frontend application URL
    required: true
  api-url:
    description: Backend API URL
    required: true

runs:
  using: composite
  steps:
  - name: Mask sensitive inputs
    shell: bash
    run: |
      echo "::add-mask::${{ inputs.aws-access-key-id }}"
      echo "::add-mask::${{ inputs.aws-secret-access-key }}"
      echo "::add-mask::${{ inputs.app-url }}"
      echo "::add-mask::${{ inputs.api-url }}"

  - name: Set up AWS CLI
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}

  - name: Install Lightsail plugin
    shell: bash
    run: |
      curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      chmod +x /usr/local/bin/lightsailctl

  - name: Build and push Docker image
    env:
      LIGHTSAIL_SERVICE_NAME: jaja-frontend
      CONTAINER_NAME: frontend
    shell: bash
    run: |
      # Build Docker image
      docker build -t ${LIGHTSAIL_SERVICE_NAME}-${CONTAINER_NAME}:${{ github.sha }} --platform=linux/amd64 ./frontend

      # Push to Lightsail
      aws lightsail push-container-image \
        --service-name ${LIGHTSAIL_SERVICE_NAME} \
        --label ${CONTAINER_NAME} \
        --image ${LIGHTSAIL_SERVICE_NAME}-${CONTAINER_NAME}:${{ github.sha }}

  - name: Deploy to Lightsail
    env:
      CONTAINER_PORT: 3000
      PUBLIC_PORT: 80
      APP_URL: ${{ inputs.app-url }}
      API_URL: ${{ inputs.api-url }}
    shell: bash
    run: |
      # Mask env vars before use
      echo "::add-mask::${APP_URL}"
      echo "::add-mask::${API_URL}"

      # Create deployment JSON
      cat > lc.json << EOF
      {
        "serviceName": "${LIGHTSAIL_SERVICE_NAME}",
        "containers": {
          "${CONTAINER_NAME}": {
            "image": ":${LIGHTSAIL_SERVICE_NAME}.${CONTAINER_NAME}.latest",
            "environment": {
              "NODE_ENV": "production",
              "NEXT_PUBLIC_API_URL": "${API_URL}",
              "APP_URL": "${APP_URL}"
            },
            "ports": {
              "${CONTAINER_PORT}": "HTTP"
            }
          }
        },
        "publicEndpoint": {
          "containerName": "${CONTAINER_NAME}",
          "containerPort": ${CONTAINER_PORT},
          "healthCheck": {
            "healthyThreshold": 2,
            "unhealthyThreshold": 2,
            "timeoutSeconds": 5,
            "intervalSeconds": 10,
            "path": "/",
            "successCodes": "200-499"
          }
        }
      }
      EOF

      # Deploy to Lightsail
      aws lightsail create-container-service-deployment \
        --cli-input-json file://lc.json 